### ISSUE TITLE
there is a prob with the endpoint

### ISSUE THREAD

**Issue by MuffinCat1** [barisbored/bh-open-api-webpage#2]
I tried to connect through the endpoint, but it seems to give me an error: "Not Found" and a status code: 404.
Pls fix it or replace it if there is a new one.

the error json message:
`
{
     "error": "Not Found",
     "message": "Cannot GET /stats/id?brawlhalla_id=3145331",
     "statusCode": 404
}
`

**Comment by barisbored** [comment]
Probably you forgot to add global prefix `v1`

See, it works: https://brawlhalla.fly.dev/v1/stats/id?brawlhalla_id=3145331
